FROM raster-vision-gpu

COPY ./plugin  /opt/src/plugin
COPY ./spacenet  /opt/src/spacenet

# Install MXNet, GluonCV APIs
RUN pip install mxnet
RUN pip install gluoncv

RUN echo "Finished reading plugin Dockerfile"

CMD ["bash"]
